---
:concurrency: <%= ENV["SIDEKIQ_THREADS"]&.to_i || 20 %>
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [default, 1]
  - [eth_to_ebc_transfers, 2]
  - [eth_to_ebc_process_transfers, 1]
  - [eth_to_ebc_listen_transactions, 1]
  - [eth_to_ebc_update_tx, 2]
  - [eth_to_ebc_process_update_tx, 1]
  - [ebc_to_eth_transfers, 2]
  - [ebc_to_eth_update_tx, 2]
  - [ebc_to_eth_listen_event_logs, 1]
  - [ebc_to_eth_process_confirm_tx, 1]
  - [ebc_to_eth_process_transfers, 1]
  - [ebc_to_eth_process_update_tx, 1]
